steps:
- name: node:16.0.0
  entrypoint: npm
  args: ["install"]
- name: node:16.0.0
  entrypoint: npm
  args: ["run", "create-env"]
  env:
    - 'TEST_ENV_VAR=${_TEST_ENV_VAR}'
- name: node:16.0.0
  entrypoint: npm
  args: ["run", "build"]
- name: "gcr.io/cloud-builders/gcloud"
  args: ["app", "deploy"]
timeout: "1600s"